version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: catisdb
    volumes:
      # - "./db:/var/lib/mysql"
      - ./data/:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    networks:
      - backend

  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # ELASTIC_PASSWORD: '12345'
    volumes:
      - ./volumes/elasticsearch:/usr/lib/elasticsearch/data
    logging:
      driver: "json-file"
      options:
          max-size: "10k"
          max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  keycloak:
    image: keycloak
    user: root
    depends_on:
      - db
    links:
      - db
    environment:
#      KEYCLOAK_USER: admin
#     KEYCLOAK_PASSWORD: admin
      DB_DATABASE: keycloak
      DB_VENDOR: MYSQL
      DB_ADDR: 141.95.103.210
      DB_PORT: 3308
      DB_USER: root
      DB_PASSWORD: root
    restart: always
    volumes:
      - keycloak-data:/var/lib/keycloak/data
      - ./imports:/opt/jboss/keycloak/imports
    command:  
      - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - 8090:8080
      - 8443:8443
    networks:
      - backend

  caisse:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - keycloak
      - db
      - elasticsearch
    restart: always
    volumes:
      - DITROS-VT:/opt
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/uuidstring?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KEYCLOAK_AUTH: http://141.95.103.210:8090/auth
    ports:
      - "8086:8080"
    networks:
      - backend   
    # links:
    #   - db
    #   - redis-server      

volumes:
  DITROS-VT:
  keycloak-data:

networks: 
    - backend
    - frontend
