
filebeat.inputs:
- type: docker
  combine_partial: true
  processors:
    - add_docker_metadata: ~
  containers:
    path: "/var/lib/docker/containers"
    stream: "stdout"
    ids:
      - "*"
    exclude_labels:
      - 'service=elasticsearch'
      - 'service=kibana'
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]


# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
  # username: "elastic_username"
  # password: "elastic_password"