scrape_configs:
  - job_name: 'MTCAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8086','host.docker.internal:8080','host.docker.internal:6379','host.docker.internal:3308']
        labels:
          application: 'mtcbackend'